local-upload: Fix Windows paths.

diff --git a/scripts/local-upload b/scripts/local-upload
--- a/scripts/local-upload
+++ b/scripts/local-upload
@@ -14,12 +14,17 @@
 #       Used to populate environment, typically containing lines
 #       like 'export CLOUDSMITH_API_KEY=xxxxx'. This file should be
 #       protected from other users, normally 600. 
-
-if [ ! -f ~/.config/local-build.rc ]; then
-    echo "Can't find configuration file ~/.config/local-build.rc. Giving up"
-    exit 1
+if [ -d /c ]; then  # windows
+    config_file="$APPDATA/local-build.rc"
+else
+    config_file="~/.config/local-build.rc"
 fi
-source ~/.config/local-build.rc
+if [[ -z  "$CLOUDSMITH_API_KEY" && ! -f "$config_file" ]]; then
+    echo "Can't find configuration file $config_file Giving up"
+    exit 1
+else
+    source $config_file
+fi
 
 if [ $# -eq 1 ]; then
     cd $1
