Verify shared library versions

diff --git a/ci/upload.sh.in b/ci/upload.sh.in
--- a/ci/upload.sh.in
+++ b/ci/upload.sh.in
@@ -19,10 +19,67 @@ fi
 echo "Using CLOUDSMITH_API_KEY: ${CLOUDSMITH_API_KEY:0:4}..."
 
 if [ -f ~/.uploadrc ]; then source ~/.uploadrc; fi
-set -x
 
-sha_xml=$(sed -n '/<tarball-checksum>/s! *<tarball-checksum> \([^ ]*\) </tarball-checksum> *!\1!p' < '@pkg_xmlname@.xml')
-sha_file=$(sha256sum '@pkg_tarname@.tar.gz')
+if [[ ( '@pkg_tarname@' =~ wx32 ) || ( '@pkg_tarname@' =~ flatpak ) ]]
+then 
+  # Verify that any dll/dylib in the tar depends on wxWidgets 3.2
+
+  EXTRACT_DIR="/tmp/extract"
+  OLD_DIR="${PWD}"
+
+  [ -d "${EXTRACT_DIR}" ] && rm -rf "${EXTRACT_DIR}"
+  mkdir "${EXTRACT_DIR}"
+  pushd "${EXTRACT_DIR}"
+  tar xzf "${OLD_DIR}/@pkg_tarname@.tar.gz"
+  find . -name '*.so' | while read -r i
+  do
+    if [ -f "${i}" ]
+    then
+      if objdump -p "${i}" | grep -q libwx >/dev/null
+      then
+        if objdump -p "${i}" | grep -q WXU_3.2 >/dev/null
+        then
+          echo "Verified that ${i} requires wxWidgets 3.2"
+        else
+          echo "ERROR: ${i} requires a version of wxWidgets is not version 3.2"
+          objdump -p "${i}" | grep libwx
+          exit 1
+        fi
+      else
+        echo "${i} does not require wxWidgets"
+      fi
+    fi
+  done
+  find . -name '*.dylib' | while read -r i
+  do
+    if otool -L "${i}" | grep -q libwx > /dev/null
+    then
+      if otool -L "${i}" | grep -q 3.2 >/dev/null
+      then
+        echo "Verified that ${i} requires wxWidgets 3.2"
+      else
+        echo "ERROR: ${i} requires a version of wxWidgets is not version 3.2"
+        otool -L "${i}" | grep libwx
+        exit 1
+      fi
+    fi
+  done
+  popd
+fi
+
+sha_exe=sha256sum
+which "${sha_exe}" || sha_exe='shasum -a 256'
+test="$(echo 'test' | $sha_exe)"
+if [ "$test" = "f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2  -" ]
+then
+  :
+else
+  echo "ERROR: No working shasum or sha256sum found"
+  exit 1
+fi
+
+sha_xml="$(sed -n '/<tarball-checksum>/s! *<tarball-checksum> \([^ ]*\) </tarball-checksum> *!\1!p' < '@pkg_xmlname@.xml')"
+sha_file="$(${sha_exe} '@pkg_tarname@.tar.gz' | sed 's/ .*//')"
 if [ "${sha_xml:-}" != "${sha_file:-}" ]
 then
   echo "ERROR: MISMATCH IN CHECKSUM"
@@ -30,7 +87,11 @@ then
   echo "${sha_xml} = @pkg_xmlname@.xml"
   cat '@pkg_xmlname@.xml'
   exit 1
+else
+  echo "Verified checksum is ${sha_xml}"
 fi
+
+set -x
 
 cloudsmith push raw --no-wait-for-sync \
     --name @pkg_displayname@-metadata \
